export const CHANGE_BEZEICHNUNG = 'CHANGE_BEZEICHNUNG';
export const CHANGE_DAUER = 'CHANGE_DAUER';
export const CHANGE_VORGÄNGER = 'CHANGE_VORGÄNGER';
export const CHANGE_NACHFOLGER = 'CHANGE_NACHFOLGER';
